sudo: required
language: python
services:
- docker

script:
- docker image build -t williamcowherd/assignment2 .

after_success:
  #log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take built images and push to DOcker hub
  - docker push williamcowherd/assignment2
  #test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "cps847_Assignment_2"
  env: "Cps847assignment2-env"
  bucket_name: "elasticbeanstalk-us-east-1-826912866381"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY